# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# no-multiple-blanks: false # MD012
line-length: # MD013
  line_length: 120
  code_block_line_length: 120
  tables: false
