# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  nerdFontsVersion: "3"

services:
  'gitlab.admin.ehealth.sundhed.dk': 'gitlab:gitlab.admin.ehealth.sundhed.dk'
