apiVersion: v1
clusters:
- cluster:
    server: https://k8s-oidc.dev1.tcs.trifork.dev:443
  name: scannet-tcs-dev-1
- cluster:
    server: https://k8s-oidc.test1.tcs.trifork.dev:443
  name: scannet-tcs-test-1
contexts:
- context:
    cluster: scannet-tcs-dev-1
    user: scannet-tcs-dev-1-ai
  name: scannet-tcs-dev-1-ai
- context:
    cluster: scannet-tcs-test-1
    user: scannet-tcs-test-1-ai
  name: scannet-tcs-test-1-ai
current-context: scannet-tcs-test-1-ai
kind: Config
users:
- name: scannet-tcs-dev-1-ai
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - scannet-tcs-dev-1
      command: /home/hcnp/src/trifork/tcs/tcs-clusters/scripts/k8s-ai-token.sh
      env: null
      interactiveMode: Never
      provideClusterInfo: false
- name: scannet-tcs-test-1-ai
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - scannet-tcs-test-1
      command: /home/hcnp/src/trifork/tcs/tcs-clusters/scripts/k8s-ai-token.sh
      env: null
      interactiveMode: Never
      provideClusterInfo: false
